server:
  port: 8083

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: ${MONGODB_URI:*********************************************s}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:****t}
    password: ${RABBITMQ_PASSWORD:****t}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
